### PR TITLE
Add straight installation instructions

### PR DESCRIPTION
**Pull request by Flinner**

### CODE REVIEW

**Comment by artsi0m** [comment]
You should've create pull request in the repository that you forked, not you own fork.

**Comment by Flinner** [comment]
ouch, Thanks!

**Comment by Flinner** [comment]
How did you find this pull request :sweat_smile: ?

**Comment by artsi0m** [comment]
I don't remember exactly, but most likely it was [Ilya](https://github.com/ichernyshovvv/) who told me about your repo and that pull request.

This spring I told him that i will help him with package, because i also found it useful, and i was already trying to use timeblocking with gCAL + gTasks and my alma-mater schedule (iis.bsuir.by), unfortunately i don't know much of elisp (or lisp in general) yet, therefore i tried to help him in other possible ways, like answering in some of the issues or something like that.

BTW: 
Pull requesting is not the only possible way to contribute using git, there is also `git send-email` which linux kernel uses.
And `git format-patch`, so you can send your patches some other interesting or even bizarre way like sending it in discord server. Just be sure that utilized messenger would not corrupt it, if it does, send patch as attachment.
https://git-send-email.io

But anyway, i spoke with Ilya about it and he said that pull request are more handy for him at this moment.

If you want to read manual about this features of git type `man git-send-email` or `man git-format-patch`

And also English is not my mother tongue, so i will be sorry if there are some mistakes in my answser.

**Comment by Flinner** [comment]
thanks for the info !! very useful!!!

**Pull request merged**
